services:
  - type: web
    name: algoforall-arbedge
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: ODDS_API_KEY
        value: 7333149b3219b7cbdd02f36b5d3827c4
      - key: REDIS_URL
        value: ""
      - key: MIN_ARB_PROFIT
        value: "0.5"
      - key: ODDS_REFRESH_INTERVAL
        value: "3600"
